refactor: improve deployment file

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -111,6 +111,12 @@ jobs:
           name: image-digests
           path: digests/
 
+      - name: Checkout local repo
+        uses: actions/checkout@v4
+        with:
+            token: ${{ secrets.GITHUB_TOKEN }}
+            path: local
+
       - name: Checkout GitOps repo
         uses: actions/checkout@v4
         with:
@@ -119,44 +125,26 @@ jobs:
           path: gitops
 
       - name: Create or update deployment file for ${{ matrix.app }}
-        run: |
+        run: | 
           cd gitops
-          DIGEST=$(cat ../digests/${{ matrix.app }})
+          
           DEPLOYMENT_DIR="apps/${{ needs.check-bump.outputs.event_repo }}-${{ matrix.app }}"
           DEPLOYMENT_FILE="$DEPLOYMENT_DIR/deployment.yaml"
+          
+          DIGEST=$(cat ../digests/${{ matrix.app }})
           APP_NAME="${{ needs.check-bump.outputs.event_repo }}-${{ matrix.app }}"
           
-          mkdir -p "$DEPLOYMENT_DIR"
-          if [ ! -f "$DEPLOYMENT_FILE" ]; then
-            echo "Creating new deployment file: $DEPLOYMENT_FILE"
-            cat > "$DEPLOYMENT_FILE" << EOF
-          apiVersion: apps/v1
-          kind: Deployment
-          metadata:
-            name: $APP_NAME
-            namespace: default
-          spec:
-            replicas: 1
-            selector:
-              matchLabels:
-                app: $APP_NAME
-            template:
-              metadata:
-                labels:
-                  app: $APP_NAME
-              spec:
-                containers:
-                - name: $APP_NAME
-                  image: ghcr.io/${{ needs.check-bump.outputs.repo }}-${{ matrix.app }}@$DIGEST
-                  ports:
-                  - containerPort: 8080
-          EOF
-            echo "Deployment file created successfully"
-          else
-            echo "Updating existing deployment file: $DEPLOYMENT_FILE"
-            sed -i "s|image: ghcr.io/${{ needs.check-bump.outputs.repo }}-${{ matrix.app }}@.*|image: ghcr.io/${{ needs.check-bump.outputs.repo }}-${{ matrix.app }}@$DIGEST|" "$DEPLOYMENT_FILE"
-            echo "Deployment file updated successfully"
+          TEMPLATE_FILE="../local/deployment/deployment-${{ matrix.app }}.template.yaml"
+          
+          if [ ! -f "$TEMPLATE_FILE" ]; then
+            echo "❌ Template not found: $TEMPLATE_FILE"
+            exit 1
           fi
+          
+          mkdir -p "$DEPLOYMENT_DIR"
+          sed "s|DOCKER_IMAGE_SOURCE|$IMAGE|g" "$TEMPLATE_FILE" > "$DEPLOYMENT_FILE"
+
+          echo "✅ Deployment written to $DEPLOYMENT_FILE"
 
       - name: Commit and push changes for ${{ needs.check-bump.outputs.event_repo }}-${{ matrix.app }}
         run: |
